export default {
  background: {
    default: "#fafafa",
    paper: "#fff",
    paperDark: "rgba(0, 0, 0, 0.38)",
    hover: "#ddd",
    active: "#ddd",
  },
  border: {
    light: "#ddd",
  },
  text: {
    primary: "rgba(0, 0, 0, 0.87)",
    secondary: "rgba(0, 0, 0, 0.54)",
    disabled: "rgba(0, 0, 0, 0.38)",
    with: "#f0f0f0",
    withDark: "#757575cc",
  },
  palette: {
    mode: "light",
    primary: {
      main: "#3E2C8A",
      light: "#9881D9",
      dark: "#1B115C",
    },
    secondary: {
      main: "#00DB03",
      light: "#89FF66",
      dark: "#00931A",
    },
    info: {
      main: "#ddd",
      light: "#66E0FF",
      dark: "#0081CB",
    },
  },
  backgroundIcons: "#757575cc",

  typography: {
    fontFamily: "'Lato', sans-serif",
    fontSize: 14,
    fontWeightLight: 300,
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    fontWeightBold: 700,
    h1: {
      fontSize: "2rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    h2: {
      fontSize: "2rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    h3: {
      fontSize: "1.5rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    h4: {
      fontSize: "1.5rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    h5: {
      fontSize: "1.25rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    h6: {
      fontSize: "1.3rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    subtitle1: {
      fontSize: "1rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    subtitle2: {
      fontSize: "0.875rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    body1: {
      fontSize: "1.2rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    body2: {
      fontSize: "0.875rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    button: {
      fontSize: "0.875rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    caption: {
      fontSize: "0.75rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    overline: {
      fontSize: "0.625rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
  },
};
