export const MoviesMock = [
  {
    id: 1,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: false,
  },
  {
    id: 2,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: true,
  },
  {
    id: 3,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: false,
  },
  {
    id: 4,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: true,
  },
  {
    id: 5,
    title: "The Shawshank Redemption",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    dt_lancamento: "10/05/1991",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: false,
  },
  {
    id: 6,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: true,
  },
  {
    id: 7,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: false,
  },
  {
    id: 8,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: true,
  },
  {
    id: 9,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: false,
  },
  {
    id: 10,
    title: "The Shawshank Redemption",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    dt_lancamento: "10/05/1991",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: true,
  },
  {
    id: 11,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: false,
  },
  {
    id: 12,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: true,
  },
  {
    id: 13,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: false,
  },
  {
    id: 14,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: true,
  },
  {
    id: 15,
    title: "The Shawshank Redemption",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    dt_lancamento: "10/05/1991",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: false,
  },
  {
    id: 16,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: true,
  },
  {
    id: 17,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: false,
  },
  {
    id: 18,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: true,
  },
  {
    id: 19,
    title: "The Shawshank Redemption",
    dt_lancamento: "10/05/1991",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: false,
  },
  {
    id: 20,
    title: "The Shawshank Redemption",
    banner:
      "https://assistironline.net/wp-content/uploads/elementor/thumbs/assistir-Jogos-de-Guerra-O-Codigo-Mortal-2008-online-owe0m7wcszmoofoszl8vfq4mfaqqa4ddfzk9niv5x4.jpg",
    dt_lancamento: "10/05/1991",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    stars: "7",
    price: "23,00",
    isFavorite: true,
  },
];
